# Generated by Django 5.2.4 on 2025-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_booking_created_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
