# Generated by Django 5.2.4 on 2025-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0008_maintenancerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bathrooams',
            new_name='bathrooms',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('villa', 'Villa'), ('house', 'House')], max_length=50),
        ),
    ]
