# Generated by Django 5.2.4 on 2025-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_rename_bathrooams_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
